site_name: SmartFridge - Dokumentation
site_url: https://smartfridge.henristr.de/docs

repo_url: https://github.com/henristr/SmartFridgePWA
repo_name: henristr/SmartFridgePWA

nav:
  - Startseite: index.md
  - Installation: installation.md
  - API: api.md
  - Sicherheit: sicherheit.md
  - Administration: admin.md
  - Troubleshooting: troubleshooting.md
    
extra:
  homepage: https://smartfridge.henristr.de

theme:
  name: material

  logo: assets/logo.png

  favicon: images/favicon.png

  language: de

  icon:
    repo: fontawesome/brands/github

  font:
    text: Montserrat
    code: Red Hat Mono

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: deep orange

  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.follow

    - search.highlight
    - search.share

    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  # Standard
  - attr_list
  - md_in_html
  - admonition

  # Code Blöcke
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Tabs
  - pymdownx.tabbed:
      alternate_style: true

  # Collapsible Admonitions
  - pymdownx.details

  # Mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Emojis & Icons
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
